//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAnd_AccountingOfEquipment
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceMovement
    {
        public int ID_DeviceMovement { get; set; }
        public int Device { get; set; }
        public System.DateTime DateOfMovement { get; set; }
        public int Employee { get; set; }
        public int PreviousRoom { get; set; }
        public int NewRoom { get; set; }
    
        public virtual Device Device1 { get; set; }
        public virtual Room Room { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Room Room1 { get; set; }
    }
}
