//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAnd_AccountingOfEquipment
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftwareInstallation
    {
        public int ID_SoftwareInstallation { get; set; }
        public int Device { get; set; }
        public int Software { get; set; }
    
        public virtual Device Device1 { get; set; }
        public virtual Software Software1 { get; set; }
    }
}
