//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAnd_AccountingOfEquipment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Software
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Software()
        {
            this.SoftwareInstallation = new HashSet<SoftwareInstallation>();
        }
    
        public int ID_Software { get; set; }
        public string Name { get; set; }
        public string LicenseKey { get; set; }
        public Nullable<int> LicenseKeyDuration { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> DateOfPurchase { get; set; }
        public int SoftwareType { get; set; }
        public bool KeyNeed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftwareInstallation> SoftwareInstallation { get; set; }
        public virtual SoftwareType SoftwareType1 { get; set; }
    }
}
